### ISSUE TITLE
reformat code to fit Google C++ Style Guide

### ISSUE THREAD

**Issue by Guenael** [Guenael/rtlsdr-wsprd#29]
https://google.github.io/styleguide/cppguide.html

**Comment by Guenael** [comment]
Done, with clang-format
```yaml
---
BasedOnStyle: Google
ColumnLimit: 0
UseTab: Never
---
Language: Cpp
SortIncludes: false
IndentWidth: 4
---
```
