### ISSUE TITLE
Setup a build pipeline for this project

### ISSUE THREAD

**Issue by Guenael** [Guenael/rtlsdr-wsprd#30]
TODO: format check + build pipeline, to check any MR on master + build release system

Some idea to start with GitHub (not very familiar, I only known GitLab CI/CD system)

```
name: CI Build pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "INFO -- This job was automatically triggered by a ${{ github.event_name }} event on a ${{ runner.os }} server"
      - run: echo "INFO -- Branch name: ${{ github.ref }} Repo name: ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install OS dependencies
        run: apt-get install build-essential cmake libfftw3-dev libusb-1.0-0-dev libcurl4-gnutls-dev librtlsdr-dev
      - name: Install cpplint # install cpplint with pip before
        run: pip install cpplint
      - name: Build
        run: make
      - name: Test
        run: echo "TODO"
      - name: DBG_status
        run: echo "INFO -- Status: ${{ job.status }}"
```
